package de.objectcode.time4u.migrator.server05.old.entities;
// Generated 06.10.2008 17:02:23 by Hibernate Tools 3.2.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OldForeignservers generated by hbm2java
 */
@Entity
@Table(name="FOREIGNSERVERS"
)
public class OldForeignservers  implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  
     private Long id;
     private boolean automatic;
     private String pullUrl;
     private boolean pullProjectTasks;
     private boolean pullWorkItems;
     private String pushUrl;
     private boolean pushProjectTasks;
     private boolean pushWorkItems;
     private long pullProjectRevision;
     private long pushProjectRevision;
     private String foreignName;
     private String myName;
     private Date maxWorkItemDay;
     private Date minWorkItemDay;
     private Long projectId;

    public OldForeignservers() {
    }

	
    public OldForeignservers(boolean automatic, String pullUrl, boolean pullProjectTasks, boolean pullWorkItems, String pushUrl, boolean pushProjectTasks, boolean pushWorkItems, long pullProjectRevision, long pushProjectRevision, String foreignName, String myName) {
        this.automatic = automatic;
        this.pullUrl = pullUrl;
        this.pullProjectTasks = pullProjectTasks;
        this.pullWorkItems = pullWorkItems;
        this.pushUrl = pushUrl;
        this.pushProjectTasks = pushProjectTasks;
        this.pushWorkItems = pushWorkItems;
        this.pullProjectRevision = pullProjectRevision;
        this.pushProjectRevision = pushProjectRevision;
        this.foreignName = foreignName;
        this.myName = myName;
    }
    public OldForeignservers(boolean automatic, String pullUrl, boolean pullProjectTasks, boolean pullWorkItems, String pushUrl, boolean pushProjectTasks, boolean pushWorkItems, long pullProjectRevision, long pushProjectRevision, String foreignName, String myName, Date maxWorkItemDay, Date minWorkItemDay, Long projectId) {
       this.automatic = automatic;
       this.pullUrl = pullUrl;
       this.pullProjectTasks = pullProjectTasks;
       this.pullWorkItems = pullWorkItems;
       this.pushUrl = pushUrl;
       this.pushProjectTasks = pushProjectTasks;
       this.pushWorkItems = pushWorkItems;
       this.pullProjectRevision = pullProjectRevision;
       this.pushProjectRevision = pushProjectRevision;
       this.foreignName = foreignName;
       this.myName = myName;
       this.maxWorkItemDay = maxWorkItemDay;
       this.minWorkItemDay = minWorkItemDay;
       this.projectId = projectId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="automatic", nullable=false)
    public boolean isAutomatic() {
        return this.automatic;
    }
    
    public void setAutomatic(boolean automatic) {
        this.automatic = automatic;
    }
    
    @Column(name="pullURL", nullable=false, length=200)
    public String getPullUrl() {
        return this.pullUrl;
    }
    
    public void setPullUrl(String pullUrl) {
        this.pullUrl = pullUrl;
    }
    
    @Column(name="pullProjectTasks", nullable=false)
    public boolean isPullProjectTasks() {
        return this.pullProjectTasks;
    }
    
    public void setPullProjectTasks(boolean pullProjectTasks) {
        this.pullProjectTasks = pullProjectTasks;
    }
    
    @Column(name="pullWorkItems", nullable=false)
    public boolean isPullWorkItems() {
        return this.pullWorkItems;
    }
    
    public void setPullWorkItems(boolean pullWorkItems) {
        this.pullWorkItems = pullWorkItems;
    }
    
    @Column(name="pushURL", nullable=false, length=200)
    public String getPushUrl() {
        return this.pushUrl;
    }
    
    public void setPushUrl(String pushUrl) {
        this.pushUrl = pushUrl;
    }
    
    @Column(name="pushProjectTasks", nullable=false)
    public boolean isPushProjectTasks() {
        return this.pushProjectTasks;
    }
    
    public void setPushProjectTasks(boolean pushProjectTasks) {
        this.pushProjectTasks = pushProjectTasks;
    }
    
    @Column(name="pushWorkItems", nullable=false)
    public boolean isPushWorkItems() {
        return this.pushWorkItems;
    }
    
    public void setPushWorkItems(boolean pushWorkItems) {
        this.pushWorkItems = pushWorkItems;
    }
    
    @Column(name="pullProjectRevision", nullable=false)
    public long getPullProjectRevision() {
        return this.pullProjectRevision;
    }
    
    public void setPullProjectRevision(long pullProjectRevision) {
        this.pullProjectRevision = pullProjectRevision;
    }
    
    @Column(name="pushProjectRevision", nullable=false)
    public long getPushProjectRevision() {
        return this.pushProjectRevision;
    }
    
    public void setPushProjectRevision(long pushProjectRevision) {
        this.pushProjectRevision = pushProjectRevision;
    }
    
    @Column(name="foreignName", nullable=false, length=30)
    public String getForeignName() {
        return this.foreignName;
    }
    
    public void setForeignName(String foreignName) {
        this.foreignName = foreignName;
    }
    
    @Column(name="myName", nullable=false, length=30)
    public String getMyName() {
        return this.myName;
    }
    
    public void setMyName(String myName) {
        this.myName = myName;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="maxWorkItemDay", length=19)
    public Date getMaxWorkItemDay() {
        return this.maxWorkItemDay;
    }
    
    public void setMaxWorkItemDay(Date maxWorkItemDay) {
        this.maxWorkItemDay = maxWorkItemDay;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="minWorkItemDay", length=19)
    public Date getMinWorkItemDay() {
        return this.minWorkItemDay;
    }
    
    public void setMinWorkItemDay(Date minWorkItemDay) {
        this.minWorkItemDay = minWorkItemDay;
    }
    
    @Column(name="project_id")
    public Long getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }




}


