package de.objectcode.time4u.migrator.server05.old.entities;
// Generated 06.10.2008 17:02:23 by Hibernate Tools 3.2.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * OldPersons generated by hbm2java
 */
@Entity
@Table(name="PERSONS"
    , uniqueConstraints = @UniqueConstraint(columnNames="userId") 
)
public class OldPersons  implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  
     private Long id;
     private String name;
     private String userId;
     private String hashedPassword;
     private String email;
     private Date lastSynchronize;
     private Long revision;

    public OldPersons() {
    }

	
    public OldPersons(String name, String userId, String hashedPassword) {
        this.name = name;
        this.userId = userId;
        this.hashedPassword = hashedPassword;
    }
    public OldPersons(String name, String userId, String hashedPassword, String email, Date lastSynchronize, Long revision) {
       this.name = name;
       this.userId = userId;
       this.hashedPassword = hashedPassword;
       this.email = email;
       this.lastSynchronize = lastSynchronize;
       this.revision = revision;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="userId", unique=true, nullable=false, length=30)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    
    @Column(name="hashedPassword", nullable=false, length=100)
    public String getHashedPassword() {
        return this.hashedPassword;
    }
    
    public void setHashedPassword(String hashedPassword) {
        this.hashedPassword = hashedPassword;
    }
    
    @Column(name="email", length=200)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="lastSynchronize", length=19)
    public Date getLastSynchronize() {
        return this.lastSynchronize;
    }
    
    public void setLastSynchronize(Date lastSynchronize) {
        this.lastSynchronize = lastSynchronize;
    }
    
    @Column(name="revision")
    public Long getRevision() {
        return this.revision;
    }
    
    public void setRevision(Long revision) {
        this.revision = revision;
    }




}


