package de.objectcode.time4u.migrator.server05.old.entities;
// Generated 06.10.2008 17:02:23 by Hibernate Tools 3.2.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OldPersonPermissions generated by hbm2java
 */
@Entity
@Table(name="PERSON_PERMISSIONS"
)
public class OldPersonPermissions  implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  
     private Long id;
     private Integer type;
     private boolean canAdmin;
     private boolean canCreate;
     private boolean canDelete;
     private boolean canRead;
     private boolean canUpdate;
     private Long projectId;
     private Long personId;
     private Long teamId;

    public OldPersonPermissions() {
    }

	
    public OldPersonPermissions(boolean canAdmin, boolean canCreate, boolean canDelete, boolean canRead, boolean canUpdate) {
        this.canAdmin = canAdmin;
        this.canCreate = canCreate;
        this.canDelete = canDelete;
        this.canRead = canRead;
        this.canUpdate = canUpdate;
    }
    public OldPersonPermissions(Integer type, boolean canAdmin, boolean canCreate, boolean canDelete, boolean canRead, boolean canUpdate, Long projectId, Long personId, Long teamId) {
       this.type = type;
       this.canAdmin = canAdmin;
       this.canCreate = canCreate;
       this.canDelete = canDelete;
       this.canRead = canRead;
       this.canUpdate = canUpdate;
       this.projectId = projectId;
       this.personId = personId;
       this.teamId = teamId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="type")
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    
    @Column(name="canAdmin", nullable=false)
    public boolean isCanAdmin() {
        return this.canAdmin;
    }
    
    public void setCanAdmin(boolean canAdmin) {
        this.canAdmin = canAdmin;
    }
    
    @Column(name="canCreate", nullable=false)
    public boolean isCanCreate() {
        return this.canCreate;
    }
    
    public void setCanCreate(boolean canCreate) {
        this.canCreate = canCreate;
    }
    
    @Column(name="canDelete", nullable=false)
    public boolean isCanDelete() {
        return this.canDelete;
    }
    
    public void setCanDelete(boolean canDelete) {
        this.canDelete = canDelete;
    }
    
    @Column(name="canRead", nullable=false)
    public boolean isCanRead() {
        return this.canRead;
    }
    
    public void setCanRead(boolean canRead) {
        this.canRead = canRead;
    }
    
    @Column(name="canUpdate", nullable=false)
    public boolean isCanUpdate() {
        return this.canUpdate;
    }
    
    public void setCanUpdate(boolean canUpdate) {
        this.canUpdate = canUpdate;
    }
    
    @Column(name="project_id")
    public Long getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }
    
    @Column(name="person_id")
    public Long getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(Long personId) {
        this.personId = personId;
    }
    
    @Column(name="team_id")
    public Long getTeamId() {
        return this.teamId;
    }
    
    public void setTeamId(Long teamId) {
        this.teamId = teamId;
    }




}


