package de.objectcode.time4u.migrator.server05.old.entities;
// Generated 06.10.2008 15:53:41 by Hibernate Tools 3.2.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OldPersonsToTeams generated by hbm2java
 */
@Entity
@Table(name="PERSONS_TO_TEAMS"
    ,catalog="time4u"
)
public class OldPersonsToTeams  implements java.io.Serializable {


     private OldPersonsToTeamsId id;

    public OldPersonsToTeams() {
    }

    public OldPersonsToTeams(OldPersonsToTeamsId id) {
       this.id = id;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="personId", column=@Column(name="person_id", nullable=false) ), 
        @AttributeOverride(name="teamId", column=@Column(name="team_id", nullable=false) ) } )
    public OldPersonsToTeamsId getId() {
        return this.id;
    }
    
    public void setId(OldPersonsToTeamsId id) {
        this.id = id;
    }




}


