package de.objectcode.time4u.migrator.server05.old.entities;
// Generated 06.10.2008 17:02:23 by Hibernate Tools 3.2.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OldProjects generated by hbm2java
 */
@Entity
@Table(name="PROJECTS"
)
public class OldProjects  implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  
     private Long id;
     private String name;
     private boolean active;
     private boolean deleted;
     private Long parentId;
     private String description;
     private Long revision;
     private String parentKey;

    public OldProjects() {
    }

	
    public OldProjects(String name, boolean active, boolean deleted) {
        this.name = name;
        this.active = active;
        this.deleted = deleted;
    }
    public OldProjects(String name, boolean active, boolean deleted, Long parentId, String description, Long revision, String parentKey) {
       this.name = name;
       this.active = active;
       this.deleted = deleted;
       this.parentId = parentId;
       this.description = description;
       this.revision = revision;
       this.parentKey = parentKey;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="name", nullable=false, length=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="active", nullable=false)
    public boolean isActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }
    
    @Column(name="deleted", nullable=false)
    public boolean isDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
    
    @Column(name="parent_id")
    public Long getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }
    
    @Column(name="description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="revision")
    public Long getRevision() {
        return this.revision;
    }
    
    public void setRevision(Long revision) {
        this.revision = revision;
    }
    
    @Column(name="parentKey", length=65535)
    public String getParentKey() {
        return this.parentKey;
    }
    
    public void setParentKey(String parentKey) {
        this.parentKey = parentKey;
    }




}


