package de.objectcode.time4u.migrator.server05.old.entities;
// Generated 06.10.2008 17:02:23 by Hibernate Tools 3.2.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * OldReportdefs generated by hbm2java
 */
@Entity
@Table(name="REPORTDEFS"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class OldReportdefs  implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  
     private Long id;
     private String name;
     private String reportData;

    public OldReportdefs() {
    }

	
    public OldReportdefs(String name) {
        this.name = name;
    }
    public OldReportdefs(String name, String reportData) {
       this.name = name;
       this.reportData = reportData;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="name", unique=true, nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="reportData", length=65535)
    public String getReportData() {
        return this.reportData;
    }
    
    public void setReportData(String reportData) {
        this.reportData = reportData;
    }




}


