package de.objectcode.time4u.migrator.server04.old.entities;
// Generated 06.10.2008 17:02:23 by Hibernate Tools 3.2.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OldDayinfos generated by hbm2java
 */
@Entity
@Table(name="DAYINFOS"
)
public class OldDayinfos  implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  
     private Long id;
     private Long revision;
     private Date day;
     private int regularTime;
     private long personId;

    public OldDayinfos() {
    }

	
    public OldDayinfos(Date day, int regularTime, long personId) {
        this.day = day;
        this.regularTime = regularTime;
        this.personId = personId;
    }
    public OldDayinfos(Long revision, Date day, int regularTime, long personId) {
       this.revision = revision;
       this.day = day;
       this.regularTime = regularTime;
       this.personId = personId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="revision")
    public Long getRevision() {
        return this.revision;
    }
    
    public void setRevision(Long revision) {
        this.revision = revision;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="day", nullable=false, length=19)
    public Date getDay() {
        return this.day;
    }
    
    public void setDay(Date day) {
        this.day = day;
    }
    
    @Column(name="regularTime", nullable=false)
    public int getRegularTime() {
        return this.regularTime;
    }
    
    public void setRegularTime(int regularTime) {
        this.regularTime = regularTime;
    }
    
    @Column(name="person_id", nullable=false)
    public long getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(long personId) {
        this.personId = personId;
    }




}


