package de.objectcode.time4u.migrator.server04.old.entities;
// Generated 06.10.2008 17:02:23 by Hibernate Tools 3.2.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OldDayinfosHistory generated by hbm2java
 */
@Entity
@Table(name="DAYINFOS_HISTORY"
)
public class OldDayinfosHistory  implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  
     private Long id;
     private Date day;
     private Date performedAt;
     private int regularTime;
     private long personId;
     private long dayInfoId;
     private long performedById;

    public OldDayinfosHistory() {
    }

    public OldDayinfosHistory(Date day, Date performedAt, int regularTime, long personId, long dayInfoId, long performedById) {
       this.day = day;
       this.performedAt = performedAt;
       this.regularTime = regularTime;
       this.personId = personId;
       this.dayInfoId = dayInfoId;
       this.performedById = performedById;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="day", nullable=false, length=19)
    public Date getDay() {
        return this.day;
    }
    
    public void setDay(Date day) {
        this.day = day;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="performedAt", nullable=false, length=19)
    public Date getPerformedAt() {
        return this.performedAt;
    }
    
    public void setPerformedAt(Date performedAt) {
        this.performedAt = performedAt;
    }
    
    @Column(name="regularTime", nullable=false)
    public int getRegularTime() {
        return this.regularTime;
    }
    
    public void setRegularTime(int regularTime) {
        this.regularTime = regularTime;
    }
    
    @Column(name="person_id", nullable=false)
    public long getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(long personId) {
        this.personId = personId;
    }
    
    @Column(name="dayInfo_id", nullable=false)
    public long getDayInfoId() {
        return this.dayInfoId;
    }
    
    public void setDayInfoId(long dayInfoId) {
        this.dayInfoId = dayInfoId;
    }
    
    @Column(name="performedBy_id", nullable=false)
    public long getPerformedById() {
        return this.performedById;
    }
    
    public void setPerformedById(long performedById) {
        this.performedById = performedById;
    }




}


