package de.objectcode.time4u.migrator.server04.old.entities;
// Generated 06.10.2008 17:02:23 by Hibernate Tools 3.2.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * OldSendChanges generated by hbm2java
 */
@Entity
@Table(name="SEND_CHANGES"
    , uniqueConstraints = @UniqueConstraint(columnNames={"owner_id", "type", "entityId"}) 
)
public class OldSendChanges  implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  
     private Long id;
     private int type;
     private long revision;
     private long entityId;
     private boolean acknowledged;
     private long ownerId;

    public OldSendChanges() {
    }

    public OldSendChanges(int type, long revision, long entityId, boolean acknowledged, long ownerId) {
       this.type = type;
       this.revision = revision;
       this.entityId = entityId;
       this.acknowledged = acknowledged;
       this.ownerId = ownerId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="type", nullable=false)
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    
    @Column(name="revision", nullable=false)
    public long getRevision() {
        return this.revision;
    }
    
    public void setRevision(long revision) {
        this.revision = revision;
    }
    
    @Column(name="entityId", nullable=false)
    public long getEntityId() {
        return this.entityId;
    }
    
    public void setEntityId(long entityId) {
        this.entityId = entityId;
    }
    
    @Column(name="acknowledged", nullable=false)
    public boolean isAcknowledged() {
        return this.acknowledged;
    }
    
    public void setAcknowledged(boolean acknowledged) {
        this.acknowledged = acknowledged;
    }
    
    @Column(name="owner_id", nullable=false)
    public long getOwnerId() {
        return this.ownerId;
    }
    
    public void setOwnerId(long ownerId) {
        this.ownerId = ownerId;
    }




}


