package de.objectcode.time4u.migrator.server04.old.entities;
// Generated 06.10.2008 17:02:23 by Hibernate Tools 3.2.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OldTodos generated by hbm2java
 */
@Entity
@Table(name="TODOS"
)
public class OldTodos  implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  
     private Long id;
     private int priority;
     private String header;
     private String description;
     private boolean completed;
     private Date completedat;
     private Date createdon;
     private Date deadline;
     private long taskId;
     private Long reporterId;
     private Long personId;
     private Long teamId;
     private Long revision;

    public OldTodos() {
    }

	
    public OldTodos(int priority, String header, String description, boolean completed, Date createdon, long taskId) {
        this.priority = priority;
        this.header = header;
        this.description = description;
        this.completed = completed;
        this.createdon = createdon;
        this.taskId = taskId;
    }
    public OldTodos(int priority, String header, String description, boolean completed, Date completedat, Date createdon, Date deadline, long taskId, Long reporterId, Long personId, Long teamId, Long revision) {
       this.priority = priority;
       this.header = header;
       this.description = description;
       this.completed = completed;
       this.completedat = completedat;
       this.createdon = createdon;
       this.deadline = deadline;
       this.taskId = taskId;
       this.reporterId = reporterId;
       this.personId = personId;
       this.teamId = teamId;
       this.revision = revision;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="priority", nullable=false)
    public int getPriority() {
        return this.priority;
    }
    
    public void setPriority(int priority) {
        this.priority = priority;
    }
    
    @Column(name="header", nullable=false, length=100)
    public String getHeader() {
        return this.header;
    }
    
    public void setHeader(String header) {
        this.header = header;
    }
    
    @Column(name="description", nullable=false, length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="completed", nullable=false)
    public boolean isCompleted() {
        return this.completed;
    }
    
    public void setCompleted(boolean completed) {
        this.completed = completed;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="completedat", length=19)
    public Date getCompletedat() {
        return this.completedat;
    }
    
    public void setCompletedat(Date completedat) {
        this.completedat = completedat;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdon", nullable=false, length=19)
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deadline", length=19)
    public Date getDeadline() {
        return this.deadline;
    }
    
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }
    
    @Column(name="task_id", nullable=false)
    public long getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(long taskId) {
        this.taskId = taskId;
    }
    
    @Column(name="reporter_id")
    public Long getReporterId() {
        return this.reporterId;
    }
    
    public void setReporterId(Long reporterId) {
        this.reporterId = reporterId;
    }
    
    @Column(name="person_id")
    public Long getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(Long personId) {
        this.personId = personId;
    }
    
    @Column(name="team_id")
    public Long getTeamId() {
        return this.teamId;
    }
    
    public void setTeamId(Long teamId) {
        this.teamId = teamId;
    }
    
    @Column(name="revision")
    public Long getRevision() {
        return this.revision;
    }
    
    public void setRevision(Long revision) {
        this.revision = revision;
    }




}


