package de.objectcode.time4u.migrator.server04.old.entities;
// Generated 06.10.2008 17:02:23 by Hibernate Tools 3.2.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OldTimepolicies generated by hbm2java
 */
@Entity
@Table(name="TIMEPOLICIES"
)
public class OldTimepolicies  implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  
     private Long id;
     private long revision;
     private Date validFrom;
     private Date validUntil;
     private int mondayTime;
     private int tuesdayTime;
     private int wednesdayTime;
     private int thursdayTime;
     private int fridayTime;
     private int saturdayTime;
     private int sundayTime;
     private long personId;

    public OldTimepolicies() {
    }

    public OldTimepolicies(long revision, Date validFrom, Date validUntil, int mondayTime, int tuesdayTime, int wednesdayTime, int thursdayTime, int fridayTime, int saturdayTime, int sundayTime, long personId) {
       this.revision = revision;
       this.validFrom = validFrom;
       this.validUntil = validUntil;
       this.mondayTime = mondayTime;
       this.tuesdayTime = tuesdayTime;
       this.wednesdayTime = wednesdayTime;
       this.thursdayTime = thursdayTime;
       this.fridayTime = fridayTime;
       this.saturdayTime = saturdayTime;
       this.sundayTime = sundayTime;
       this.personId = personId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="revision", nullable=false)
    public long getRevision() {
        return this.revision;
    }
    
    public void setRevision(long revision) {
        this.revision = revision;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="validFrom", nullable=false, length=19)
    public Date getValidFrom() {
        return this.validFrom;
    }
    
    public void setValidFrom(Date validFrom) {
        this.validFrom = validFrom;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="validUntil", nullable=false, length=19)
    public Date getValidUntil() {
        return this.validUntil;
    }
    
    public void setValidUntil(Date validUntil) {
        this.validUntil = validUntil;
    }
    
    @Column(name="mondayTime", nullable=false)
    public int getMondayTime() {
        return this.mondayTime;
    }
    
    public void setMondayTime(int mondayTime) {
        this.mondayTime = mondayTime;
    }
    
    @Column(name="tuesdayTime", nullable=false)
    public int getTuesdayTime() {
        return this.tuesdayTime;
    }
    
    public void setTuesdayTime(int tuesdayTime) {
        this.tuesdayTime = tuesdayTime;
    }
    
    @Column(name="wednesdayTime", nullable=false)
    public int getWednesdayTime() {
        return this.wednesdayTime;
    }
    
    public void setWednesdayTime(int wednesdayTime) {
        this.wednesdayTime = wednesdayTime;
    }
    
    @Column(name="thursdayTime", nullable=false)
    public int getThursdayTime() {
        return this.thursdayTime;
    }
    
    public void setThursdayTime(int thursdayTime) {
        this.thursdayTime = thursdayTime;
    }
    
    @Column(name="fridayTime", nullable=false)
    public int getFridayTime() {
        return this.fridayTime;
    }
    
    public void setFridayTime(int fridayTime) {
        this.fridayTime = fridayTime;
    }
    
    @Column(name="saturdayTime", nullable=false)
    public int getSaturdayTime() {
        return this.saturdayTime;
    }
    
    public void setSaturdayTime(int saturdayTime) {
        this.saturdayTime = saturdayTime;
    }
    
    @Column(name="sundayTime", nullable=false)
    public int getSundayTime() {
        return this.sundayTime;
    }
    
    public void setSundayTime(int sundayTime) {
        this.sundayTime = sundayTime;
    }
    
    @Column(name="person_id", nullable=false)
    public long getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(long personId) {
        this.personId = personId;
    }




}


