package de.objectcode.time4u.migrator.server04.old.entities;
// Generated 06.10.2008 17:02:23 by Hibernate Tools 3.2.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OldWorkitems generated by hbm2java
 */
@Entity
@Table(name="WORKITEMS"
)
public class OldWorkitems  implements java.io.Serializable {

  private static final long serialVersionUID = 1L;
  
     private Long id;
     private String wcomment;
     private Date wend;
     private Date wbegin;
     private long taskId;
     private long personId;
     private Long todoId;
     private long projectId;

    public OldWorkitems() {
    }

	
    public OldWorkitems(String wcomment, Date wend, Date wbegin, long taskId, long personId, long projectId) {
        this.wcomment = wcomment;
        this.wend = wend;
        this.wbegin = wbegin;
        this.taskId = taskId;
        this.personId = personId;
        this.projectId = projectId;
    }
    public OldWorkitems(String wcomment, Date wend, Date wbegin, long taskId, long personId, Long todoId, long projectId) {
       this.wcomment = wcomment;
       this.wend = wend;
       this.wbegin = wbegin;
       this.taskId = taskId;
       this.personId = personId;
       this.todoId = todoId;
       this.projectId = projectId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="wComment", nullable=false, length=65535)
    public String getWcomment() {
        return this.wcomment;
    }
    
    public void setWcomment(String wcomment) {
        this.wcomment = wcomment;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="wEnd", nullable=false, length=19)
    public Date getWend() {
        return this.wend;
    }
    
    public void setWend(Date wend) {
        this.wend = wend;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="wBegin", nullable=false, length=19)
    public Date getWbegin() {
        return this.wbegin;
    }
    
    public void setWbegin(Date wbegin) {
        this.wbegin = wbegin;
    }
    
    @Column(name="task_id", nullable=false)
    public long getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(long taskId) {
        this.taskId = taskId;
    }
    
    @Column(name="person_id", nullable=false)
    public long getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(long personId) {
        this.personId = personId;
    }
    
    @Column(name="todo_id")
    public Long getTodoId() {
        return this.todoId;
    }
    
    public void setTodoId(Long todoId) {
        this.todoId = todoId;
    }
    
    @Column(name="project_id", nullable=false)
    public long getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(long projectId) {
        this.projectId = projectId;
    }




}


